on:
  push:
    branches:
      - "main"

name: Continous integration
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo clippy --all-features -- -D warnings

  deploy:
    runs-on: ubuntu-latest
    needs: clippy_check
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
          no-test: "true"
