on:
  push:
    branches:
      - "main"

name: Continous integration
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo clippy --all-features -- -D warnings

  deploy:
    runs-on: ubuntu-latest
    needs: clippy_check
    steps:
      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01JDSWHDHZB8MK3T9C8W8VC575
          secrets: |
            WEBHOOK_URL = '${{ secrets.WEBHOOK_URL }}'
            TELOXIDE_TOKEN = '${{ secrets.TELOXIDE_TOKEN }}'
